/**:
  ros__parameters:
    ciecle_range: 0.5
    jump_pointnumber: 5.0
    vel_forward_setting: 0.8
    target_x: 0.08
    target_y: 9.0

    # Physical parameters
    uav_weight: 3.34
    control_frequency: 100
    hover_throttle: 0.5
    thrust_ratio: 2.5

    # Hover PD + DOB
    hover_wn_xy: 1.0
    hover_zeta_xy: 1.0
    hover_wn_z: 2.0
    hover_zeta_z: 1.0
    dob_L_xy: 1.0
    dob_L_z: 1.0

    # Position PID
    position_X_P: 1.0
    position_X_I: 0.0
    position_X_D: 0.05
    position_Y_P: 1.0
    position_Y_I: 0.0
    position_Y_D: 0.05
    position_Z_P: 1.0
    position_Z_I: 0.0
    position_Z_D: 0.0

    # Velocity PID
    vel_X_P: 1.8
    vel_X_I: 0.0
    vel_X_D: 0.3
    vel_Y_P: 5.0
    vel_Y_I: 0.0
    vel_Y_D: 0.3
    vel_Z_P: 1.0
    vel_Z_I: 0.0
    vel_Z_D: 0.0

    # Acceleration PID
    acc_X_P: 0.0
    acc_X_I: 0.0
    acc_X_D: 0.0
    acc_Y_P: 0.0
    acc_Y_I: 0.0
    acc_Y_D: 0.0
    acc_Z_P: 0.0
    acc_Z_I: 0.0
    acc_Z_D: 0.0

    # Lateral velocity PID
    vel_X_T_P: 4.0
    vel_X_T_I: 0.2
    vel_X_T_D: 0.03
    vel_Y_T_P: 4.0
    vel_Y_T_I: 0.2
    vel_Y_T_D: 0.03
    vel_Z_T_P: 0.55
    vel_Z_T_I: 0.2
    vel_Z_T_D: 0.0

    # Velocity limits
    vel_X_limit: 10.0
    vel_Y_limit: 10.0
    vel_Z_limit: 10.0

    # Attitude limits
    roll_limit: 30.0
    pitch_limit: 30.0
    high_limit: 30.0
